-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.proveedores1
(
    id serial,
    nombre character varying(30),
    direccion text,
    telefono character varying(20),
    correo character varying(60),
    PRIMARY KEY (id),
    UNIQUE (correo)
);

CREATE TABLE IF NOT EXISTS public.productos1
(
    id serial,
    proveedor_id integer,
    nombre character varying(30),
    precio numeric(13, 2),
    exitencia integer,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.productos1
    ADD FOREIGN KEY (proveedor_id)
    REFERENCES public.proveedores1 (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;