-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.alumnos
(
    id serial,
    nombre character varying(80),
    apellido character varying(80),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.asignaturas
(
    id serial,
    nombre character varying(80),
    descripcion text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.alumnos_asignaturas
(
    alumnos_id integer,
    asignaturas_id integer,
    PRIMARY KEY (alumnos_id, asignaturas_id)
);

ALTER TABLE IF EXISTS public.alumnos_asignaturas
    ADD FOREIGN KEY (alumnos_id)
    REFERENCES public.alumnos (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.alumnos_asignaturas
    ADD FOREIGN KEY (asignaturas_id)
    REFERENCES public.asignaturas (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;

END;